baseURL = 'https://quickwrite.net/'
languageCode = 'en-us'
title = 'QuickWrite'

theme = "monospace-web"

[params]
    [params.license]
        name = "CC BY-SA 4.0"
        url = "https://creativecommons.org/licenses/by-sa/4.0/"
