baseURL = 'https://quickwrite.net/'
languageCode = 'en-us'
title = 'QuickWrite'

enableRobotsTXT = true
theme = "monospace-web"

[params]
    [params.license]
        name = "CC BY-SA 4.0"
        url = "https://creativecommons.org/licenses/by-sa/4.0/"

[menus]
    [[menus.left]]
        name = 'Home'
        pageRef = '/'
        weight = 10
    [[menus.left]]
        name = 'About'
        pageRef = '/about'
        weight = 20
    
    [[menus.right]]
        name = 'Blog'
        pageRef = '/blog'
        weight = 10

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = false
        noClasses = false
        style = 'algol_nu'
        tabWidth = 4
        wrapperClass = 'highlight'
